### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by zhmzm** [haoyangliASTAPLE/3DFed#3]
Hi,
Your paper is wonderful. The thoughts of each module are artful. I really like your work and want to follow it.

I encounter some difficulties in running your code. I run the command `python training.py --name mnist --params configs/mnist_fed.yaml`. But the ModuleNotFoundError is reported. The full error log is the following.
```
Traceback (most recent call last):
  File "~/3DFed/training.py", line 92, in <module>
    helper = Helper(params)
  File "~/3DFed/helper.py", line 41, in __init__
    self.make_attack()
  File "~/3DFed/helper.py", line 85, in make_attack
    raise ModuleNotFoundError(f'Your attack: {self.params.attack} should '
ModuleNotFoundError: Your attack: ThrDFed should be defined either ThrDFed (3DFed) or                                         ModelReplace (Model Replacement Attack)
```
I am not sure if I made any mistake on the command or the configs file (both of them are unchanged). Could you please guide me to run it properly?

**Comment by zhmzm** [comment]
It is caused by missing the hdbscan library.
